# Generated by Django 3.2.9 on 2021-11-10 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='important',
            field=models.BooleanField(default=False, verbose_name='Важность'),
        ),
    ]
